repos:
- repo: local
  hooks:
  - id: project-precommit
    name: Project pre-commit hook
    entry: npm run pre-commit
    language: system
    pass_filenames: false
    verbose: true
  - id: prettier
    name: Run prettier
    entry: ./scripts/githooks/format-prettier.sh
    language: script
    pass_filenames: true
- repo: local
  hooks:
  - id: scan-secrets
    name: Scan secrets
    entry: ./scripts/githooks/scan-secrets.sh
    args: ["check=staged-changes"]
    language: script
    pass_filenames: false
- repo: local
  hooks:
  - id: check-file-format
    name: Check file format
    entry: ./scripts/githooks/check-file-format.sh
    args: ["check=staged-changes"]
    language: script
    pass_filenames: false
- repo: local
  hooks:
  - id: check-markdown-format
    name: Check Markdown format
    entry: ./scripts/githooks/check-markdown-format.sh
    args: ["check=staged-changes"]
    language: script
    pass_filenames: false
- repo: local
  hooks:
  - id: check-english-usage
    name: Check English usage
    entry: ./scripts/githooks/check-english-usage.sh
    args: ["check=staged-changes"]
    language: script
    pass_filenames: false
- repo: local
  hooks:
  - id: lint-terraform
    name: Lint Terraform
    entry: ./scripts/githooks/check-terraform-format.sh
    language: script
    pass_filenames: false
