fail_fast: true

repos:
  - repo: local
    hooks:
      - id: talisman-precommit
        name: Talisman pre-commit hook
        entry: talisman --githook pre-commit
        language: system
        pass_filenames: false
        types: [ text ]
        verbose: true
      - id: project-precommit
        name: Project pre-commit hook
        entry: yarn run pre-commit
        language: system
        pass_filenames: false
        verbose: true
