export const HUB_PAGE_TITLE = "Vaccinations - NHS App";
export const SCHEDULE_PAGE_TITLE = "Vaccines for all ages - NHS App";
export const RSV_PAGE_TITLE = "RSV Vaccine - NHS App";
export const FLU_PAGE_TITLE = "Flu Vaccine - NHS App";
export const COVID_PAGE_TITLE = "COVID-19 Vaccine - NHS App";
export const PNEUMO_PAGE_TITLE = "Pneumococcal Vaccine - NHS App";
export const SHINGLES_PAGE_TITLE = "Shingles Vaccine - NHS App";
export const SIX_IN_ONE_PAGE_TITLE = "6-in-1 Vaccine - NHS App";
export const MENACWY_PAGE_TITLE = "MenACWY Vaccine - NHS App";
