%% To build (from project root): uv run --with mermaid-cli mmdc -i docs/diagrams/vita-branch-strat.mmd -o docs/diagrams/vita-branch-strat.png -w 2048

gitGraph
  commit
  commit tag: "v0.52.0"
  commit
  commit tag: "v0.52.1"
  branch "release/v1.0"
  commit tag: "v1.0.0-rc1"
  checkout main
  commit tag: "v1.1.0"
  checkout "release/v1.0"
  commit id: "fix-1" type: HIGHLIGHT
  commit tag: "v1.0.0-rc2"
  checkout main
  cherry-pick id: "fix-1"
  commit id: ".."
  checkout "release/v1.0"
  commit tag: "v1.0.0"
  checkout main
  commit tag: "v1.x.x"
  commit id:"..."
  commit id: "fix-2" type: HIGHLIGHT
  checkout "release/v1.0"
  cherry-pick id: "fix-2"
  commit tag: "v1.0.1"
  checkout main
  commit id: "...."
  commit tag: "v1.40.0"
  branch "release/v2.0"
  commit tag: "v2.0.0-rc1"
  checkout main
  commit id: "....."
  commit tag: "v2.1.0"
  checkout "release/v2.0"
  commit tag: "v2.0.0"
