export const AWS_PRIMARY_REGION = "eu-west-2";

export enum ClientSideErrorTypes {
  UNHANDLED_ERROR = "UNHANDLED_ERROR",
  UNHANDLED_PROMISE_REJECT_ERROR = "UNHANDLED_PROMISE_REJECT_ERROR",
  UNHANDLED_ERROR_DURING_RENDER = "UNHANDLED_ERROR_DURING_RENDER",
  UNKNOWN_ERROR_REASON = "UNKNOWN_ERROR_REASON",
}
