name: run-contract-tests
description: "Run contract tests"

inputs:
  target_ref:
    description: "Target ref to run tests on"
    required: true

runs:
  using: "composite"
  steps:
    #################################################
    # Run contract tests
    #################################################

    - name: "Checkout target code"
      uses: actions/checkout@v5
      with:
        ref: ${{ inputs.target_ref }}
        path: "code-for-contract-tests"

    - name: "Cache node modules"
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./code-for-contract-tests/**/package-lock.json') }}

    - name: "Install dependencies"
      shell: bash
      working-directory: "./code-for-contract-tests"
      run: |
        npm ci --ignore-scripts

    - name: "Run contract tests ${{inputs.environment}}"
      shell: bash
      working-directory: "./code-for-contract-tests"
      run: |
        npm run contract
