name: "Check file format"
description: "Check file format"
runs:
  using: "composite"
  steps:
    - name: "Check file format"
      shell: bash
      run: |
        check=all ./scripts/githooks/check-file-format.sh
