name: "Check Markdown format"
description: "Check Markdown format"
runs:
  using: "composite"
  steps:
    - name: "Check Markdown format"
      shell: bash
      run: |
        check=all ./scripts/githooks/check-markdown-format.sh
