name: "CI/CD snapshot upload"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true
        type: string

env:
  AWS_REGION: eu-west-2
  AWS_S3_ARTEFACTS_BUCKET: vita-${{ secrets.AWS_ACCOUNT_ID }}-artefacts-dev

jobs:
  upload-snapshots:
    name: "Upload Snapshots to S3"
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    env:
      IAM_ROLE: ${{ secrets.IAM_ROLE }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Configure AWS credentials for S3 upload"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: GitHubActionsSessionUpload
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "Copy ${{ inputs.tag }} tagged snapshots to reference"
        run: |
          aws s3 sync s3://${{ env.AWS_S3_ARTEFACTS_BUCKET }}/playwright/${{ inputs.tag }}/ s3://${{ env.AWS_S3_ARTEFACTS_BUCKET }}/playwright/reference/__snapshots__/
