name: "Snapshot Test stage"

on:
  workflow_call:
    inputs:
      checkout_ref:
        description: "Ref to checkout"
        required: true
        type: string

env:
  AWS_REGION: eu-west-2
  AWS_S3_ARTEFACTS_BUCKET: vita-${{ secrets.AWS_ACCOUNT_ID }}-artefacts-preprod

jobs:
  snapshot-test:
    name: "Snapshot Test"
    runs-on: ubuntu-latest
    environment:
      name: preprod
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    env:
      TEST_NHS_APP_URL: ${{ secrets.TEST_NHS_APP_URL }}
      TEST_NHS_LOGIN_PASSWORD: ${{ secrets.TEST_NHS_LOGIN_PASSWORD }}
      TEST_NHS_LOGIN_OTP: ${{ secrets.TEST_NHS_LOGIN_OTP }}
      TEST_APP_URL: ${{ secrets.TEST_APP_URL }}
      VITA_TEST_USER_PATTERN: ${{ secrets.VITA_TEST_USER_PATTERN }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.checkout_ref }}

      - name: "Configure AWS credentials for environment"
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "Install dependencies"
        run: |
          npm ci --ignore-scripts

      - name: "Get current week number and playwright version"
        id: cache_key_values
        run: |
          echo "week_num=$(date -u +'%Y-%V')" | tee -a $GITHUB_OUTPUT
          echo "playwright_version=$(npm view @playwright/test version)" | tee -a $GITHUB_OUTPUT

      - name: "Cache Playwright browsers"
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.cache_key_values.outputs.week_num }}-${{ steps.cache_key_values.outputs.playwright_version }}-${{ hashFiles('**/playwright.config*') }}

      - name: "Install Playwright browsers"
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: |
          npx playwright install --with-deps

      - name: "Download snapshots from S3 bucket"
        run: |
          aws s3 sync s3://${{ env.AWS_S3_ARTEFACTS_BUCKET }}/playwright/reference/ ./e2e/snapshot/

      - name: "Run Playwright snapshot tests (no update)"
        run: |
          npm run e2e:snapshot -- --config=playwright.config.cross-browser.ts

      - name: "Upload snapshots to S3 bucket with tag ${{ github.ref_name }}"
        if: failure()
        run: |
          aws s3 sync ./e2e/snapshot/snapshot_review/ s3://${{ env.AWS_S3_ARTEFACTS_BUCKET }}/playwright/${{ github.ref_name }}/

      - name: "Upload report"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-snapshot
          path: playwright-report/
          retention-days: 30
