name: "Snapshot Test stage"

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag of deployment"
        required: true
        type: string

env:
  AWS_REGION: eu-west-2
  AWS_S3_ARTEFACTS_BUCKET: vita-${{ secrets.AWS_ACCOUNT_ID }}-artefacts-preprod

jobs:
  snapshot-test:
    name: "Snapshot Test"
    runs-on: ubuntu-latest
    environment:
      name: preprod
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    env:
      TEST_NHS_APP_USERNAME: ${{ secrets.TEST_NHS_APP_USERNAME }}
      TEST_NHS_APP_PASSWORD: ${{ secrets.TEST_NHS_APP_PASSWORD }}
      TEST_NHS_APP_URL: ${{ secrets.TEST_NHS_APP_URL }}
      TEST_NHS_LOGIN_PASSWORD: ${{ secrets.TEST_NHS_LOGIN_PASSWORD }}
      TEST_NHS_LOGIN_OTP: ${{ secrets.TEST_NHS_LOGIN_OTP }}
      TEST_APP_URL: ${{ secrets.TEST_APP_URL }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Configure AWS credentials for environment"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "Install dependencies"
        run: |
          npm ci --ignore-scripts

      - name: "Install Playwright browsers"
        run: |
          npx playwright install --with-deps

      - name: "Download snapshots from S3 bucket"
        run: |
          aws s3 sync s3://${{ env.AWS_S3_ARTEFACTS_BUCKET }}/playwright/reference/ ./e2e/snapshot/

      - name: "Run Playwright snapshot tests (no update)"
        run: |
          npm run e2e:snapshot

      - name: "Upload snapshots to S3 bucket with tag ${{ inputs.tag }}"
        if: failure()
        run: |
          aws s3 sync ./e2e/snapshot/snapshot_review/ s3://${{ env.AWS_S3_ARTEFACTS_BUCKET }}/playwright/${{ inputs.tag }}/

      - name: "Upload report"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
